# Generated by Django 5.2.9 on 2025-12-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID', max_length=100, null=True),
        ),
    ]
