# Generated by Django 5.2.9 on 2025-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
