# Generated by Django 5.2.9 on 2025-12-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password_reset_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_otp_expires_at',
            new_name='password_reset_otp_created_at',
        ),
    ]
