# Generated by Django 5.2.9 on 2025-12-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_password_reset_otp_expires_at_user_password_reset_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
