# Generated by Django 5.2.9 on 2025-12-25 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_branch_alter_category_options_branchproduct'),
        ('users', '0008_user_otp_failed_attempts_user_otp_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, help_text='Branch this staff member is assigned to (for branch-specific access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='products.branch'),
        ),
    ]
