from django.core.management.base import BaseCommand
from products.models import Juice


class Command(BaseCommand):
    help = 'Seed batch 3: Nut shakes, Faloodas, Mojitos, Thick Shakes, Creams, Bowls'

    def get_products(self):
        return [
            # NUT-BASED MILKSHAKES (5)
            {'id': 56, 'name': 'Kaju Anjeer Milkshake', 'description': 'A premium, thick blend of creamy Cashews and fiber-rich Figs (Anjeer). A luxurious shake that offers a perfect balance of crunch and sweetness.', 'long_description': 'This shake is the ultimate energy dense treat. We blend soaked figs with premium grade cashews and fresh milk. The result is a naturally sweet, textured drink that is packed with minerals and healthy fats to keep you going all day.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Rich in Minerals", "Premium Nuts", "No Added Sugar", "No Preservatives", "Textured Blend"], 'benefits': [{"title": "Stamina Builder", "description": "High calorie and nutrient density for physical strength."}, {"title": "Bone Health", "description": "Excellent source of calcium and magnesium for strong bones."}, {"title": "Gut Health", "description": "High fiber from figs supports healthy digestion."}], 'nutrition_calories': 240.00, 'nutrition_total_fat': 10.5, 'nutrition_carbohydrate': 32.0, 'nutrition_dietary_fiber': 3.8, 'nutrition_total_sugars': 24.0, 'nutrition_protein': 6.5, 'ingredients': 'Premium Cashews, Dried Figs, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Nuts (Cashews).'},
            
            {'id': 57, 'name': 'Kesar Badam Milkshake', 'description': 'A timeless Indian classic. Pure saffron (Kesar) and crushed almonds (Badam) blended into creamy milk for a royal and nourishing experience.', 'long_description': 'Our Kesar Badam shake is made the traditional way. We use real saffron strands for color and aroma, combined with almonds that provide a subtle crunch and a boost of Vitamin E. It\'s a brain-boosting drink that\'s great for all ages.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Real Saffron", "Crushed Almonds", "Always Fresh", "No Preservatives", "Brain Food"], 'benefits': [{"title": "Brain Power", "description": "Almonds are rich in riboflavin and L-carnitine for cognitive health."}, {"title": "Skin & Hair", "description": "High Vitamin E content promotes healthy skin and hair."}, {"title": "Immunity", "description": "Saffron and minerals help strengthen the body\'s natural defenses."}], 'nutrition_calories': 210.00, 'nutrition_total_fat': 9.2, 'nutrition_carbohydrate': 22.0, 'nutrition_dietary_fiber': 2.0, 'nutrition_total_sugars': 18.0, 'nutrition_protein': 7.2, 'ingredients': 'Blanched Almonds, Saffron Strands, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Nuts (Almonds).'},
            
            {'id': 58, 'name': 'Kaju Badam Milkshake', 'description': 'The powerhouse of nuts. A creamy, protein-rich blend of Cashews and Almonds that provides a heavy, satisfying, and nutty flavor.', 'long_description': 'A premium dual-nut shake combining the buttery richness of cashews with the crunchy goodness of almonds.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Double Nut Power", "High Protein", "Always Fresh", "No Preservatives", "Creamy Finish"], 'benefits': [{"title": "Muscle Support", "description": "High protein content helps in muscle maintenance and repair."}, {"title": "Healthy Fats", "description": "Rich in monounsaturated fats that are good for heart health."}, {"title": "Satiety", "description": "Highly filling, making it a great healthy snack between meals."}], 'nutrition_calories': 230.00, 'nutrition_total_fat': 11.5, 'nutrition_carbohydrate': 20.0, 'nutrition_dietary_fiber': 2.5, 'nutrition_total_sugars': 15.0, 'nutrition_protein': 7.8, 'ingredients': 'Premium Cashews, Almonds, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Nuts (Cashews, Almonds).'},
            
            {'id': 59, 'name': 'Kaju Milkshake', 'description': 'Silky, buttery, and incredibly smooth. This shake uses pure Cashews to create a naturally sweet and thick milk drink that feels like liquid velvet.', 'long_description': 'Made with premium cashews blended to perfection with cold milk for a luxuriously smooth texture.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Pure Cashews", "Ultra Smooth", "Always Fresh", "No Preservatives", "Buttery Texture"], 'benefits': [{"title": "Heart Health", "description": "Cashews contain zero cholesterol and are good for the heart."}, {"title": "Mineral Boost", "description": "Rich in Copper, Zinc, and Magnesium for metabolic health."}, {"title": "Quick Energy", "description": "Nutrient-dense calories for an instant pick-me-up."}], 'nutrition_calories': 225.00, 'nutrition_total_fat': 10.8, 'nutrition_carbohydrate': 21.0, 'nutrition_dietary_fiber': 1.2, 'nutrition_total_sugars': 14.0, 'nutrition_protein': 6.2, 'ingredients': 'Premium Cashews, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Nuts (Cashews).'},
            
            {'id': 60, 'name': 'Badam Pista Milkshake', 'description': 'A vibrant and nutty delight. The earthy flavor of Pistachios meets the crunch of Almonds in a beautiful, nutrient-rich shake.', 'long_description': 'This elegant shake combines the distinctive green color of pistachios with the wholesome goodness of almonds.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Premium Pista", "Crushed Badam", "Always Fresh", "No Preservatives", "Rich Color"], 'benefits': [{"title": "Eye Health", "description": "Pistachios contain lutein and zeaxanthin for vision protection."}, {"title": "Antioxidant Rich", "description": "Protects cells from damage and supports anti-aging."}, {"title": "Healthy Weight", "description": "Protein and fiber help in managing appetite effectively."}], 'nutrition_calories': 215.00, 'nutrition_total_fat': 10.2, 'nutrition_carbohydrate': 19.0, 'nutrition_dietary_fiber': 2.8, 'nutrition_total_sugars': 14.0, 'nutrition_protein': 7.5, 'ingredients': 'Roasted Pistachios, Almonds, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Nuts (Pistachios, Almonds).'},
            
            # FALOODAS (6)
            {'id': 66, 'name': 'Mumbai Special Falooda', 'description': 'A legendary street-style dessert drink. Layers of rose syrup, vermicelli, silky sabja seeds, and chilled milk, topped with a scoop of premium vanilla ice cream.', 'long_description': 'Inspired by the bustling streets of Mumbai, this Falooda is a symphony of textures. We use authentic rose petal preserves and high-quality vermicelli to ensure every sip is a perfect balance of floral sweetness and creamy delight.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Authentic Recipe", "Triple Layered", "Premium Ice Cream", "No Preservatives", "Rich & Creamy"], 'benefits': [{"title": "Naturally Cooling", "description": "Sabja seeds act as a natural coolant for the body."}, {"title": "Texture Variety", "description": "A fun mix of soft vermicelli, crunchy nuts, and smooth ice cream."}, {"title": "Instant Mood Lifter", "description": "The perfect sweet treat to brighten your day."}], 'nutrition_calories': 210.00, 'nutrition_total_fat': 6.5, 'nutrition_carbohydrate': 34.0, 'nutrition_dietary_fiber': 1.5, 'nutrition_total_sugars': 28.0, 'nutrition_protein': 4.8, 'ingredients': 'Full Cream Milk, Rose Syrup, Vermicelli, Sabja Seeds, Vanilla Ice Cream', 'allergen_info': 'Contains Milk, Contains Gluten (Vermicelli).'},
            
            {'id': 67, 'name': 'Dry Fruit Falooda', 'description': 'The ultimate luxury Falooda. Packed with a heavy dose of crushed almonds, cashews, and pistachios for a crunchy, nutty twist on the classic.', 'long_description': 'This version is for those who love crunch. We take our signature falooda base and load it with premium roasted dry fruits, offering a nutrient-dense dessert that is high in healthy fats and minerals.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Loaded with Nuts", "Premium Quality", "No Added Colors", "No Preservatives", "Extra Crunchy"], 'benefits': [{"title": "Rich in Minerals", "description": "Provides Zinc, Magnesium, and Iron from mixed nuts."}, {"title": "Healthy Fats", "description": "Nuts provide essential fatty acids for heart health."}, {"title": "High Energy", "description": "A calorie-dense treat perfect for a quick energy recharge."}], 'nutrition_calories': 255.00, 'nutrition_total_fat': 10.8, 'nutrition_carbohydrate': 32.0, 'nutrition_dietary_fiber': 2.2, 'nutrition_total_sugars': 25.0, 'nutrition_protein': 6.5, 'ingredients': 'Milk, Almonds, Cashews, Pistachios, Vermicelli, Sabja Seeds, Ice Cream', 'allergen_info': 'Contains Milk, Contains Nuts, Contains Gluten.'},
            
            {'id': 69, 'name': 'Kesar Falooda', 'description': 'A royal saffron-infused delight. A golden-hued Falooda that features the aromatic essence of pure Kesar blended with creamy milk.', 'long_description': 'This premium falooda features authentic saffron strands that impart a beautiful golden color and traditional aroma.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Pure Saffron", "Aromatic", "Always Fresh", "No Preservatives", "Royal Taste"], 'benefits': [{"title": "Aromatic Refreshment", "description": "Saffron helps in soothing the mind and reducing stress."}, {"title": "Skin Health", "description": "Traditional Kesar is known to promote a healthy skin glow."}, {"title": "Bone Support", "description": "Rich in calcium from the high-quality dairy base."}], 'nutrition_calories': 195.00, 'nutrition_total_fat': 6.2, 'nutrition_carbohydrate': 30.0, 'nutrition_dietary_fiber': 1.0, 'nutrition_total_sugars': 24.0, 'nutrition_protein': 5.0, 'ingredients': 'Milk, Pure Saffron, Vermicelli, Sabja Seeds, Kesar Ice Cream', 'allergen_info': 'Contains Milk, Contains Gluten.'},
            
            {'id': 72, 'name': 'Mango Falooda', 'description': 'A seasonal sensation. Real mango pulp layered with vermicelli and sabja seeds, topped with a delicious mango-flavored ice cream.', 'long_description': 'Features fresh alphonso mango pulp for an authentic tropical falooda experience.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Real Mango Pulp", "Seasonal Special", "Fruity & Creamy", "No Preservatives", "Vibrant Flavor"], 'benefits': [{"title": "Vitamin A Source", "description": "Rich in mango carotenoids for better eye health."}, {"title": "Natural Sweetness", "description": "Uses the natural sugars of sun-ripened mangoes."}, {"title": "Refreshing", "description": "The perfect fruit-based dessert to beat the heat."}], 'nutrition_calories': 205.00, 'nutrition_total_fat': 5.8, 'nutrition_carbohydrate': 35.0, 'nutrition_dietary_fiber': 1.8, 'nutrition_total_sugars': 29.0, 'nutrition_protein': 4.5, 'ingredients': 'Milk, Fresh Mango Pulp, Vermicelli, Sabja Seeds, Mango Ice Cream', 'allergen_info': 'Contains Milk, Contains Gluten.'},
            
            {'id': 76, 'name': 'Kulfi Falooda', 'description': 'A fusion of two legendary Indian desserts. Creamy, dense kulfi chunks served in a classic falooda base with vermicelli and sabja seeds.', 'long_description': 'Traditional kulfi made from slow-cooked milk solids for an authentic dense texture.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Traditional Kulfi", "Dense & Creamy", "Always Fresh", "No Preservatives", "Classic Taste"], 'benefits': [{"title": "Rich Texture", "description": "Slow-cooked milk solid (Kulfi) provides a deeper flavor than regular ice cream."}, {"title": "Slow Melting", "description": "Kulfi stays firm longer, making every sip consistently creamy."}, {"title": "Calcium Rich", "description": "High concentration of dairy nutrients for bone health."}], 'nutrition_calories': 240.00, 'nutrition_total_fat': 9.5, 'nutrition_carbohydrate': 32.0, 'nutrition_dietary_fiber': 1.0, 'nutrition_total_sugars': 26.0, 'nutrition_protein': 6.2, 'ingredients': 'Full Cream Milk, Traditional Kulfi Chunks, Vermicelli, Sabja Seeds, Rose Syrup', 'allergen_info': 'Contains Milk, Contains Gluten.'},
            
            {'id': 79, 'name': 'Rainbow Falooda', 'description': 'A visually stunning multi-layered dessert. Featuring different fruit syrups and jellies, creating a rainbow of flavors in one bottle.', 'long_description': 'A colorful celebration drink with multiple fruit syrups layered for a rainbow effect.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Multi-Layered", "Fruity Mix", "Kids Favorite", "No Preservatives", "Fun Textures"], 'benefits': [{"title": "Flavor Variety", "description": "A different fruit experience in every layer."}, {"title": "Cooling Seeds", "description": "Sabja seeds provide a natural cooling effect for the stomach."}, {"title": "Celebration Drink", "description": "The perfect colorful treat for special occasions."}], 'nutrition_calories': 220.00, 'nutrition_total_fat': 5.8, 'nutrition_carbohydrate': 38.0, 'nutrition_dietary_fiber': 1.2, 'nutrition_total_sugars': 32.0, 'nutrition_protein': 4.2, 'ingredients': 'Milk, Assorted Fruit Syrups, Fruit Jellies, Vermicelli, Sabja Seeds, Ice Cream', 'allergen_info': 'Contains Milk, Contains Gluten.'},
            
            # MOJITOS (3)
            {'id': 85, 'name': 'Classic Mint Mojito', 'description': 'The ultimate thirst quencher. A zesty blend of fresh lime, crushed mint leaves, and sparkling soda over ice.', 'long_description': 'Made with fresh hand-crushed mint and lime for an authentic refreshing mocktail.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Fresh Mint", "Real Lime", "Sparkling & Zesty", "No Preservatives", "Ultra Refreshing"], 'benefits': [{"title": "Digestive Relief", "description": "Mint and lime help in soothing the stomach and aiding digestion."}, {"title": "Instant Hydration", "description": "The sparkling base and citrus provide immediate refreshment."}, {"title": "Zero Fat", "description": "A light, guilt-free way to stay cool."}], 'nutrition_calories': 70.00, 'nutrition_total_fat': 0.0, 'nutrition_carbohydrate': 18.0, 'nutrition_dietary_fiber': 0.2, 'nutrition_total_sugars': 16.0, 'nutrition_protein': 0.1, 'ingredients': 'Fresh Mint, Fresh Lime, Sparkling Water/Soda, Cane Sugar', 'allergen_info': 'No Mustard, No Nuts, No Peanuts, No Sesame, No Soya, No Milk'},
            
            {'id': 87, 'name': 'Blue Lagoon', 'description': 'Cool, crisp, and tropical. A vibrant blue citrus mocktail with a hint of orange notes and a refreshing fizzy finish.', 'long_description': 'A visually striking blue mocktail with tropical citrus flavors.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Vibrant Color", "Citrus Twist", "Party Favorite", "No Preservatives", "Icy Cold"], 'benefits': [{"title": "Palate Cleanser", "description": "The sharp citrus notes help clean the palate after a heavy meal."}, {"title": "Low Calorie", "description": "A refreshing alternative to heavy milk-based drinks."}, {"title": "Mood Lifter", "description": "Refreshing carbonation and citrus flavor to boost your energy."}], 'nutrition_calories': 85.00, 'nutrition_total_fat': 0.0, 'nutrition_carbohydrate': 21.0, 'nutrition_dietary_fiber': 0.0, 'nutrition_total_sugars': 20.0, 'nutrition_protein': 0.0, 'ingredients': 'Blue Curacao (Non-alcoholic), Lime Juice, Sparkling Water, Lemon Slices', 'allergen_info': 'No Mustard, No Nuts, No Peanuts, No Sesame, No Soya, No Milk'},
            
            {'id': 91, 'name': 'Blueberry Mojito', 'description': 'A berry-infused twist on the classic. Fresh mint and lime paired with the sweet and tart flavor of blueberries.', 'long_description': 'Fresh blueberries muddled with mint and lime for a sophisticated berry mojito.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Real Blueberries", "Fresh Mint", "Tart & Sweet", "No Preservatives", "Antioxidant Hint"], 'benefits': [{"title": "Antioxidant Boost", "description": "Blueberries are known for their high levels of protective antioxidants."}, {"title": "Vitamin C Rich", "description": "Lime and berries provide a natural immunity support."}, {"title": "Exotic Refreshment", "description": "A sophisticated flavor profile for mocktail lovers."}], 'nutrition_calories': 90.00, 'nutrition_total_fat': 0.1, 'nutrition_carbohydrate': 22.0, 'nutrition_dietary_fiber': 0.5, 'nutrition_total_sugars': 19.0, 'nutrition_protein': 0.2, 'ingredients': 'Fresh Blueberries, Mint Leaves, Lime Juice, Sparkling Soda', 'allergen_info': 'No Mustard, No Nuts, No Peanuts, No Sesame, No Soya, No Milk'},
            
            # THICK SHAKES (5)
            {'id': 93, 'name': 'Vanilla Shake', 'description': 'A timeless, creamy classic. Smooth vanilla bean ice cream blended with chilled milk for a simple yet elegant treat.', 'long_description': 'Our Vanilla Shake is anything but basic. We use a high-fat vanilla bean ice cream to ensure a velvety texture. It\'s a versatile shake that is loved for its clean, sweet, and comforting flavor.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Extra Creamy", "Premium Ice Cream", "Smooth Texture", "No Preservatives", "Classic Choice"], 'benefits': [{"title": "Calcium Rich", "description": "High dairy content supports healthy teeth and bones."}, {"title": "Comfort Drink", "description": "Vanilla has a naturally soothing aroma that helps reduce stress."}, {"title": "Instant Satiety", "description": "A thick and filling shake that satisfies hunger quickly."}], 'nutrition_calories': 190.00, 'nutrition_total_fat': 7.5, 'nutrition_carbohydrate': 26.0, 'nutrition_dietary_fiber': 0.0, 'nutrition_total_sugars': 22.0, 'nutrition_protein': 4.8, 'ingredients': 'Vanilla Ice Cream, Full Cream Milk', 'allergen_info': 'Contains Milk.'},
            
            {'id': 95, 'name': 'Chocolate Shake', 'description': 'A rich, cocoa-filled dream. Deep chocolate ice cream blended into a frothy, chocolatey shake that is a true cocoa-lover\'s delight.', 'long_description': 'Made with premium chocolate ice cream and Dutch cocoa for intense chocolate flavor.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Rich Cocoa", "Indulgent", "Always Fresh", "No Preservatives", "Smooth Finish"], 'benefits': [{"title": "Mood Booster", "description": "Chocolate triggers the release of endorphins for a happy feeling."}, {"title": "Energy Charge", "description": "A quick source of energy for an active afternoon."}, {"title": "Antioxidant Hint", "description": "Cocoa contains natural flavonoids that are good for the heart."}], 'nutrition_calories': 215.00, 'nutrition_total_fat': 8.2, 'nutrition_carbohydrate': 30.0, 'nutrition_dietary_fiber': 1.2, 'nutrition_total_sugars': 25.0, 'nutrition_protein': 5.2, 'ingredients': 'Chocolate Ice Cream, Cocoa Powder, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Soya (from chocolate).'},
            
            {'id': 101, 'name': 'Cold Coffee with Ice Cream', 'description': 'The perfect pick-me-up. Bold, aromatic coffee blended with milk and topped with a scoop of vanilla ice cream for a creamy caffeine kick.', 'long_description': 'Freshly brewed coffee blended with ice cream for a smooth, energizing treat.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Premium Coffee", "Double Creamy", "Always Fresh", "No Preservatives", "Caffeine Boost"], 'benefits': [{"title": "Alertness", "description": "Fresh coffee helps improve focus and concentration."}, {"title": "Refreshing Energy", "description": "The chill of the shake combined with coffee is perfect for midday slumps."}, {"title": "Metabolic Boost", "description": "Caffeine can naturally aid in boosting metabolism."}], 'nutrition_calories': 180.00, 'nutrition_total_fat': 6.8, 'nutrition_carbohydrate': 24.0, 'nutrition_dietary_fiber': 0.0, 'nutrition_total_sugars': 19.0, 'nutrition_protein': 4.5, 'ingredients': 'Fresh Brewed Coffee, Vanilla Ice Cream, Full Cream Milk', 'allergen_info': 'Contains Milk.'},
            
            {'id': 102, 'name': 'Oreo Milk Shake', 'description': 'A crunchy, cookie-filled sensation. Real Oreo cookies blended into a creamy vanilla base for the ultimate "Cookies & Cream" experience.', 'long_description': 'Loaded with crushed Oreo biscuits for authentic cookies and cream flavor.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Real Oreo Chunks", "Cookie Crunch", "Thick & Creamy", "No Preservatives", "Bestseller"], 'benefits': [{"title": "Fun Texture", "description": "Enjoy the mix of smooth cream and crunchy cookie bits."}, {"title": "Highly Filling", "description": "The cookies add a substantial feel to the shake."}, {"title": "Perfect Dessert", "description": "A great alternative to a heavy pastry or cake."}], 'nutrition_calories': 245.00, 'nutrition_total_fat': 10.5, 'nutrition_carbohydrate': 34.0, 'nutrition_dietary_fiber': 0.8, 'nutrition_total_sugars': 26.0, 'nutrition_protein': 5.0, 'ingredients': 'Oreo Biscuits, Vanilla Ice Cream, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Gluten (Wheat), Contains Soya.'},
            
            {'id': 103, 'name': 'Kitkat Shake', 'description': 'Have a break with a Kitkat Shake! Features blended Kitkat bars for a wafery, chocolatey crunch in every sip.', 'long_description': 'Real Kitkat chocolate wafer bars blended for unique crunchy texture.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Real Kitkat Bars", "Wafer Crunch", "Chocolatey Goodness", "No Preservatives", "Kids Favorite"], 'benefits': [{"title": "Unique Crunch", "description": "The wafer center of Kitkat provides a distinct, airy crunch."}, {"title": "Rich in Energy", "description": "A high-calorie treat for a quick energy replenishment."}, {"title": "Balanced Sweetness", "description": "The wafer balances the sweetness of the chocolate and milk."}], 'nutrition_calories': 235.00, 'nutrition_total_fat': 9.8, 'nutrition_carbohydrate': 32.0, 'nutrition_dietary_fiber': 0.5, 'nutrition_total_sugars': 24.0, 'nutrition_protein': 4.9, 'ingredients': 'Kitkat Wafers, Chocolate Sauce, Vanilla Ice Cream, Full Cream Milk', 'allergen_info': 'Contains Milk, Contains Gluten, Contains Soya.'},
            
            # FRUIT CREAMS (7)
            {'id': 105, 'name': 'Mix Fruit Cream', 'description': 'A luxurious medley of seasonal fruits folded into thick, sweetened fresh cream. A colorful and multi-textured dessert that is the ultimate fruit lover\'s dream.', 'long_description': 'Our Mix Fruit Cream is a signature dessert. We hand-cut fresh seasonal fruits—apples, grapes, pomegranate, and bananas—and blend them into a velvety, whipped fresh cream base. It is dense, rich, and provides a blast of different fruit flavors in every spoonful.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Fresh Fruit Chunks", "High Fat Cream", "Spoonable Texture", "No Preservatives", "Gourmet Dessert"], 'benefits': [{"title": "Vitamin Variety", "description": "Multiple fruits provide a broad spectrum of essential vitamins and minerals."}, {"title": "Rich & Filling", "description": "High-quality fats from fresh cream keep you satisfied for longer."}, {"title": "Antioxidant Rich", "description": "Fresh berries and fruits help fight oxidative stress."}], 'nutrition_calories': 260.00, 'nutrition_total_fat': 14.5, 'nutrition_carbohydrate': 30.0, 'nutrition_dietary_fiber': 2.2, 'nutrition_total_sugars': 24.0, 'nutrition_protein': 3.8, 'ingredients': 'Fresh Whipped Cream, Mixed Seasonal Fruits, Hint of Vanilla', 'allergen_info': 'Contains Milk. No Mustard, No Nuts, No Peanuts, No Sesame, No Soya.'},
            
            {'id': 106, 'name': 'Avocado Cream', 'description': 'The green gold of desserts. Buttery avocado pulp blended with premium cream for a silky, mild, and nutrient-dense treat that is incredibly satisfying.', 'long_description': 'Premium ripe avocados blended with thick cream for a unique healthy dessert.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Buttery Avocado", "Healthy Fats", "Silk Texture", "No Preservatives", "Nutrient Dense"], 'benefits': [{"title": "Omega-3 Fatty Acids", "description": "Supports brain health and lowers bad cholesterol."}, {"title": "Potassium Rich", "description": "Contains more potassium than bananas to support nerve function."}, {"title": "Long-Lasting Energy", "description": "Healthy fats provide a slow-burn energy release."}], 'nutrition_calories': 320.00, 'nutrition_total_fat': 22.0, 'nutrition_carbohydrate': 18.0, 'nutrition_dietary_fiber': 5.0, 'nutrition_total_sugars': 10.0, 'nutrition_protein': 4.2, 'ingredients': 'Ripe Avocado Pulp, Fresh Heavy Cream', 'allergen_info': 'Contains Milk.'},
            
            {'id': 108, 'name': 'Mango Cream', 'description': 'Pure Alphonso/Totapuri mango pulp and fresh mango chunks swirled into thick, luscious cream. The ultimate seasonal indulgence for mango enthusiasts.', 'long_description': 'Fresh seasonal mangoes blended with rich cream for a tropical dessert.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Real Mango Chunks", "Velvety Cream", "Seasonal Favorite", "No Preservatives", "Rich Flavor"], 'benefits': [{"title": "Vitamin A Powerhouse", "description": "Massive dose of Beta-carotene for eye and skin health."}, {"title": "Instant Mood Lifter", "description": "The rich, sweet taste of mangoes naturally boosts serotonin."}, {"title": "Energy Dense", "description": "A great source of natural fruit energy and healthy dairy fats."}], 'nutrition_calories': 280.00, 'nutrition_total_fat': 15.0, 'nutrition_carbohydrate': 34.0, 'nutrition_dietary_fiber': 1.8, 'nutrition_total_sugars': 28.0, 'nutrition_protein': 3.2, 'ingredients': 'Fresh Mango Chunks, Mango Pulp, Heavy Cream', 'allergen_info': 'Contains Milk.'},
            
            {'id': 109, 'name': 'Custard Apple Cream', 'description': 'A grainy, floral, and incredibly sweet specialty. Fresh de-seeded custard apple pulp mixed into a dense cream base for a unique traditional treat.', 'long_description': 'Meticulously de-seeded custard apple (sitaphal) blended with rich cream.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["De-seeded Fresh Pulp", "Authentic Flavor", "Unique Texture", "No Preservatives", "Premium Dessert"], 'benefits': [{"title": "Magnesium Rich", "description": "Supports heart health and helps maintain blood pressure."}, {"title": "Natural Sweetener", "description": "Sithaphal provides an intense sweetness without extra refined sugar."}, {"title": "Cooling Property", "description": "Traditional remedy known to have a cooling effect on the body."}], 'nutrition_calories': 310.00, 'nutrition_total_fat': 16.2, 'nutrition_carbohydrate': 38.0, 'nutrition_dietary_fiber': 2.5, 'nutrition_total_sugars': 32.0, 'nutrition_protein': 3.5, 'ingredients': 'Fresh Custard Apple (Sithaphal) Pulp, Thickened Fresh Cream', 'allergen_info': 'Contains Milk.'},
            
            {'id': 110, 'name': 'Strawberry Cream', 'description': 'A classic Mahabaleshwar-style treat. Freshly sliced tart strawberries layered with sweet, thick cream. A perfect balance of acidity and richness.', 'long_description': 'Fresh strawberries in thick whipped cream for a classic berry dessert.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Fresh Sliced Berries", "Whipped Cream", "Tart & Sweet", "No Preservatives", "Elegant Dessert"], 'benefits': [{"title": "Vitamin C Boost", "description": "Strawberries are a top source of Vitamin C for immunity."}, {"title": "Skin Vitality", "description": "Antioxidants in berries promote a healthy, youthful glow."}, {"title": "Low Glycemic Berries", "description": "The fruit component is low in calories and high in fiber."}], 'nutrition_calories': 240.00, 'nutrition_total_fat': 13.8, 'nutrition_carbohydrate': 26.0, 'nutrition_dietary_fiber': 2.0, 'nutrition_total_sugars': 20.0, 'nutrition_protein': 3.4, 'ingredients': 'Fresh Strawberries, Heavy Fresh Cream, Strawberry Coulis', 'allergen_info': 'Contains Milk.'},
            
            {'id': 111, 'name': 'Dragon Fruit Cream', 'description': 'An exotic, visually stunning dessert. Chunks of fresh dragon fruit mixed into a thick, velvety cream base.', 'long_description': 'Vibrant dragon fruit pieces in rich cream for an exotic treat.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Real Dragon Fruit", "Exotic Texture", "Whipped Cream", "No Preservatives", "Antioxidant Rich"], 'benefits': [{"title": "Iron Source", "description": "Natural plant-based iron for blood health."}, {"title": "Gut Health", "description": "Tiny seeds provide prebiotic fiber for digestion."}, {"title": "Magnesium Boost", "description": "Supports muscle relaxation and bone density."}], 'nutrition_calories': 250.00, 'nutrition_total_fat': 14.0, 'nutrition_carbohydrate': 28.0, 'nutrition_dietary_fiber': 2.4, 'nutrition_total_sugars': 21.0, 'nutrition_protein': 3.6, 'ingredients': 'Fresh Dragon Fruit, Heavy Cream', 'allergen_info': 'Contains Milk.'},
            
            {'id': 112, 'name': 'Chocolate Cream', 'description': 'A dream for chocolate lovers. Rich cocoa and dark chocolate shavings folded into heavy whipped cream.', 'long_description': 'Intense chocolate flavor with dark chocolate pieces in thick cream.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Rich Cocoa", "Dark Chocolate Bits", "Thick & Luscious", "No Preservatives", "Indulgent"], 'benefits': [{"title": "Mood Lifter", "description": "Cocoa helps stimulate feel-good endorphins."}, {"title": "Energy Charge", "description": "Calorie-dense for a quick stamina boost."}, {"title": "Antioxidant Hint", "description": "Dark cocoa contains heart-healthy flavonoids."}], 'nutrition_calories': 340.00, 'nutrition_total_fat': 22.0, 'nutrition_carbohydrate': 32.0, 'nutrition_dietary_fiber': 1.5, 'nutrition_total_sugars': 26.0, 'nutrition_protein': 4.5, 'ingredients': 'Heavy Cream, Cocoa Powder, Chocolate Shavings', 'allergen_info': 'Contains Milk, Contains Soya.'},
            
            # FRUIT WITH ICE CREAM (2)
            {'id': 116, 'name': 'Mix Fruit with Ice Cream', 'description': 'A refreshing fruit salad topped with premium ice cream. A perfect mix of natural fruit crunch and creamy sweetness.', 'long_description': 'Fresh cut fruits with a scoop of vanilla ice cream for balanced indulgence.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Fresh Cut Fruits", "Premium Scoop", "Always Fresh", "No Preservatives", "Duo Texture"], 'benefits': [{"title": "Full Spectrum Vitamins", "description": "Variety of fruits ensures a wide range of micronutrients."}, {"title": "Digestive Support", "description": "High fiber from whole fruit chunks helps digestion."}, {"title": "Satisfying Dessert", "description": "The perfect balance of healthy fruit and indulgent ice cream."}], 'nutrition_calories': 190.00, 'nutrition_total_fat': 6.5, 'nutrition_carbohydrate': 32.0, 'nutrition_dietary_fiber': 2.5, 'nutrition_total_sugars': 24.0, 'nutrition_protein': 3.2, 'ingredients': 'Apple, Banana, Pomegranate, Grapes, Vanilla Ice Cream', 'allergen_info': 'Contains Milk.'},
            
            {'id': 118, 'name': 'Dry Fruit with Ice Cream', 'description': 'A royal treat. Premium roasted almonds, cashews, and dates served over a generous scoop of ice cream.', 'long_description': 'Premium nuts and dried fruits with ice cream for a luxurious dessert.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Premium Nuts", "Crunchy & Sweet", "Nutrient Dense", "No Preservatives", "Luxury Treat"], 'benefits': [{"title": "Mineral Rich", "description": "Provides Zinc and Magnesium for overall vitality."}, {"title": "Healthy Fats", "description": "Nuts provide heart-healthy unsaturated fats."}, {"title": "Protein Boost", "description": "Higher protein content than standard fruit desserts."}], 'nutrition_calories': 280.00, 'nutrition_total_fat': 12.5, 'nutrition_carbohydrate': 35.0, 'nutrition_dietary_fiber': 3.2, 'nutrition_total_sugars': 26.0, 'nutrition_protein': 6.5, 'ingredients': 'Almonds, Cashews, Dates, Vanilla Ice Cream', 'allergen_info': 'Contains Milk, Contains Nuts.'},
            
            # FRUIT BOWLS (2)
            {'id': 121, 'name': 'Mix Fruit Bowl', 'description': '100% Whole fresh fruits. A clean, healthy, and fiber-packed bowl of seasonal favorites—no added sugar or dairy.', 'long_description': 'Our signature fruit bowl features bite-sized pieces of the freshest seasonal produce. Including crisp apples, sweet papaya, hydrating watermelon, and tangy pineapple.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["100% Whole Fruit", "High Fiber", "Zero Added Sugar", "Zero Dairy", "Freshly Cut"], 'benefits': [{"title": "Natural Cleanse", "description": "High fiber and water content help detoxify the body."}, {"title": "Weight Management", "description": "Low calorie but very filling due to high bulk and fiber."}, {"title": "Skin Health", "description": "Natural vitamins and hydration for a clear complexion."}], 'nutrition_calories': 95.00, 'nutrition_total_fat': 0.3, 'nutrition_carbohydrate': 24.0, 'nutrition_dietary_fiber': 4.5, 'nutrition_total_sugars': 18.0, 'nutrition_protein': 1.2, 'ingredients': 'Apple, Papaya, Watermelon, Pineapple, Pomegranate', 'allergen_info': 'No Mustard, No Nuts, No Peanuts, No Sesame, No Soya, No Milk.'},
            
            {'id': 125, 'name': 'Combo Bowl', 'description': 'Your choice, your bowl. Pick any three of our fresh seasonal fruits for a customized, healthy snack.', 'long_description': 'Customizable fruit bowl - choose any 3 fruits from our selection.', 'price': 60.00, 'net_quantity_ml': 300, 'features': ["Customizable", "Zero Added Sugar", "Always Fresh", "Fiber Rich", "Healthy Snack"], 'benefits': [{"title": "Tailored Nutrition", "description": "Pick fruits based on your specific vitamin needs."}, {"title": "Low Glycemic", "description": "A great snack choice for maintaining steady blood sugar."}, {"title": "Hydrating", "description": "Fresh whole fruits provide essential cellular hydration."}], 'nutrition_calories': 110.00, 'nutrition_total_fat': 0.4, 'nutrition_carbohydrate': 26.0, 'nutrition_dietary_fiber': 4.2, 'nutrition_total_sugars': 20.0, 'nutrition_protein': 1.4, 'ingredients': 'Selection of any 3 (Mango, Papaya, Watermelon, Apple, Kiwi, etc.)', 'allergen_info': 'No Mustard, No Nuts, No Peanuts, No Sesame, No Soya, No Milk.'},
        ]

    def handle(self, *args, **kwargs):
        products = self.get_products()
        updated_count = 0
        
        for product_data in products:
            juice_id = product_data.pop('id')
            try:
                juice = Juice.objects.get(id=juice_id)
                for key, value in product_data.items():
                    setattr(juice, key, value)
                juice.save()
                self.stdout.write(self.style.SUCCESS(f'Updated {juice.name} (ID: {juice_id})'))
                updated_count += 1
            except Juice.DoesNotExist:
                self.stdout.write(self.style.WARNING(f'Juice ID {juice_id} not found'))
        
        self.stdout.write(self.style.SUCCESS(f'\nBatch 3 Complete! Updated {updated_count} of {len(products)} products.'))
