# Generated by Django 5.2.9 on 2026-01-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_applied_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cooking_instructions',
            field=models.CharField(blank=True, default='', help_text='Special cooking instructions (e.g., less sugar, extra ice)', max_length=200),
        ),
    ]
