# Generated by Django 5.2.9 on 2025-12-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee before GST', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='18% GST on delivery fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='food_gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='5% GST on food (collected by platform)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='food_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total food cost before GST', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Platform fee (includes 18% GST)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price at time of order', max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final payable amount', max_digits=10),
        ),
    ]
