# Generated by Django 5.2.8 on 2025-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_price_order_delivery_fee_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final payable amount', max_digits=10),
        ),
    ]
