# Generated by Django 5.2.8 on 2025-12-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(editable=False, help_text='Sequential order number shown to users', null=True, unique=True),
        ),
    ]
