# Generated by Django 5.2.8 on 2025-12-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_number'),
        ('products', '0005_branch_alter_category_options_branchproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch from which this order will be fulfilled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.branch'),
        ),
    ]
