# Generated by Django 5.2.9 on 2026-01-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cooking_instructions',
            field=models.CharField(blank=True, default='', help_text='Special cooking instructions from customer', max_length=200),
        ),
    ]
