# Generated by Django 5.2.9 on 2025-12-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juice',
            name='allergen_info',
            field=models.TextField(blank=True, help_text="Allergen warnings (e.g., 'No Mustard, No Nuts, No Peanuts')"),
        ),
        migrations.AddField(
            model_name='juice',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of benefits with title and description: [{"title": "Immunity Booster", "description": "Packed with Vitamin C..."}]'),
        ),
        migrations.AddField(
            model_name='juice',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of feature tags like ["All Natural", "No Preservatives", "Always Fresh"]'),
        ),
        migrations.AddField(
            model_name='juice',
            name='ingredients',
            field=models.TextField(blank=True, help_text="Main ingredients (e.g., 'Fresh Mandarin')"),
        ),
        migrations.AddField(
            model_name='juice',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed product description for detail page'),
        ),
        migrations.AddField(
            model_name='juice',
            name='net_quantity_ml',
            field=models.IntegerField(default=250, help_text='Net quantity in ml (fixed at 250ml)'),
        ),
        migrations.AddField(
            model_name='juice',
            name='nutrition_calories',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calories per 200ml', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='juice',
            name='nutrition_carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrate in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='juice',
            name='nutrition_dietary_fiber',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dietary fiber in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='juice',
            name='nutrition_protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='juice',
            name='nutrition_total_fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fat in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='juice',
            name='nutrition_total_sugars',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total sugars in grams', max_digits=6, null=True),
        ),
    ]
