# Generated by Django 5.2.9 on 2025-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_juice_allergen_info_juice_benefits_juice_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juice',
            name='net_quantity_ml',
            field=models.IntegerField(default=300, help_text='Net quantity in ml (fixed at 250ml)'),
        ),
    ]
