# Generated by Django 5.2.8 on 2025-12-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_juice_net_quantity_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juice',
            name='net_quantity_ml',
            field=models.IntegerField(default=300, help_text='Net quantity in ml (fixed at 300ml)'),
        ),
    ]
